version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_DB: cookr
      POSTGRES_USER: cookr
      POSTGRES_PASSWORD: cookr
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@cookr.ch
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025
      - 8025:8025

  backend:
    container_name: backend
    build: packages/backend
    command: npm start
    ports:
      - 8055:8055
    volumes:
      - ./packages/backend:/directus
      - /directus/node_modules
    depends_on:
      - db
      - mailhog

  frontend:
    container_name: frontend
    build: packages/frontend
    command: npm run dev
    volumes:
      - ./packages/frontend:/srv/app
      - /srv/app/node_modules
    depends_on:
      - backend
    ports:
      - 3000:3000

volumes:
  pgdata:
