[build]
  base ="packages/frontend/"
  publish = "dist/"
  command = "sed -i \"s|API_ORIGIN_PLACEHOLDER|${API_ORIGIN}|g\" /opt/build/repo/netlify.toml && cat /opt/build/repo/netlify.toml && npm run build"

[[redirects]]
  from = "/api/*"
  to = "API_ORIGIN_PLACEHOLDER/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/uploads/*"
  to = "API_ORIGIN_PLACEHOLDER/assets/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/files/*"
  to = "API_ORIGIN_PLACEHOLDER/files/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
