/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppLayout: typeof import('./src/components/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/components/layouts/AuthLayout.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CBtn: typeof import('chusho')['CBtn']
    CCollapse: typeof import('chusho')['CCollapse']
    CCollapseBtn: typeof import('chusho')['CCollapseBtn']
    CCollapseContent: typeof import('chusho')['CCollapseContent']
    CFormGroup: typeof import('chusho')['CFormGroup']
    CIcon: typeof import('chusho')['CIcon']
    CLabel: typeof import('chusho')['CLabel']
    CPicture: typeof import('chusho')['CPicture']
    CTextarea: typeof import('chusho')['CTextarea']
    CTextField: typeof import('chusho')['CTextField']
    CurrentUser: typeof import('./src/components/CurrentUser.vue')['default']
    Errors: typeof import('./src/components/forms/Errors.vue')['default']
    ErrorsList: typeof import('./src/components/ErrorsList.vue')['default']
    Field: typeof import('vee-validate')['Field']
    FieldHelp: typeof import('./src/components/forms/FieldHelp.vue')['default']
    Form: typeof import('vee-validate')['Form']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageUploader: typeof import('./src/components/forms/ImageUploader.vue')['default']
    Label: typeof import('./src/components/forms/Label.vue')['default']
    Multiselect: typeof import('./src/components/forms/Multiselect.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Notifications: typeof import('./src/components/Notifications.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecipeAuthor: typeof import('./src/components/RecipeAuthor.vue')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    RecipeCardLoader: typeof import('./src/components/loaders/RecipeCardLoader.vue')['default']
    RecipeFavoriteBtn: typeof import('./src/components/RecipeFavoriteBtn.vue')['default']
    RecipeForm: typeof import('./src/components/RecipeForm.vue')['default']
    RecipeFormIngredients: typeof import('./src/components/RecipeFormIngredients.vue')['default']
    RecipeImage: typeof import('./src/components/RecipeImage.vue')['default']
    RecipeListItem: typeof import('./src/components/RecipeListItem.vue')['default']
    RecipeListItemLoader: typeof import('./src/components/loaders/RecipeListItemLoader.vue')['default']
    RecipeQuantity: typeof import('./src/components/RecipeQuantity.vue')['default']
    RecipesCarousel: typeof import('./src/components/RecipesCarousel.vue')['default']
    RecipesList: typeof import('./src/components/RecipesList.vue')['default']
    RecipeTime: typeof import('./src/components/RecipeTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Select: typeof import('./src/components/forms/Select.vue')['default']
    Tag: typeof import('./src/components/Tag.vue')['default']
    TagsList: typeof import('./src/components/TagsList.vue')['default']
    TagsSelect: typeof import('./src/components/TagsSelect.vue')['default']
  }
}
